- name: Install the 'Virtualization' package group
  ansible.builtin.dnf:
    name: '@virtualization'
    state: present

- name: Install DNF Package List
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ dnf_packages }}"
